spring:
  main:
      banner-mode: "off"
  profiles:
    active:
    - https
#    - https-two-way-tls
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      keys-to-sanitize:
      show-values: ALWAYS
    config-props:
      show-values: ALWAYS
logging:
  level:
    root: OFF
---
spring:
  config:
    activate:
      on-profile: https
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "localhost"
          keystore:
            location: "classpath:keystore.p12"
            password: "abcdefg"
            type: "PKCS12"
server:
  ssl:
    client-auth: "want"
    bundle: "server"
---
spring:
  config:
    activate:
      on-profile: https-two-way-tls
  ssl:
    bundle:
      jks:
        server:
          truststore:
            location: "classpath:truststore.p12"
            password: "abcdefg"
            type: "PKCS12"
server:
  ssl:
    client-auth: "need"
