spring:
  main:
      banner-mode: "off"
  profiles:
    active: https
server:
  port: 8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
logging:
  level:
    root: OFF
---
spring:
  config:
    activate:
      on-profile: https
  ssl:
    bundle:
      jks:
        server:
          key:
            alias: "localhost"
          keystore:
            location: "classpath:keystore.p12"
            password: "abcdefg"
            type: "PKCS12"
server:
  ssl:
    bundle: "server"