spring:
  main:
#    web-application-type: none
    banner-mode: "off"
  profiles:
    active:
      - https
      - https-two-way-tls
logging:
  level:
    root: OFF
server:
  port: 8090
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      keys-to-sanitize:
      show-values: ALWAYS
    config-props:
      show-values: ALWAYS
---
spring:
  config:
    activate:
      on-profile: https
  ssl:
    bundle:
      jks:
        client:
          truststore:
            location: "classpath:truststore.p12"
            password: "abcdefg"
            type: "PKCS12"
---
spring:
  config:
    activate:
      on-profile: https-two-way-tls
  ssl:
    bundle:
      jks:
        client:
          key:
            alias: "localhost"
          keystore:
            location: "classpath:keystore.p12"
            password: "abcdefg"
            type: "PKCS12"
