spring:
  main:
    web-application-type: none
    banner-mode: "off"
  profiles:
    active: https
logging:
  level:
    root: OFF
---
spring:
  config:
    activate:
      on-profile: https
  ssl:
    bundle:
      jks:
        client:
          # key:
          #   alias: "localhost"
          keystore:
            location: "classpath:keystore.p12"
            password: "abcdefg"
            type: "PKCS12"
          truststore:
            location: "classpath:truststore.p12"
            password: "abcdefg"
            type: "PKCS12"